// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WebLinterVsix
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVSPackageString = "4e737333-d498-4553-8096-b2f6fff930a2";
        public const string WebLinterCmdSetString = "214001ac-2bd3-474a-a56c-b45dcb785e96";
        public const string ConfigFileCmdSetString = "03997e40-2a1e-4241-ad40-e9296c0a58a0";
        public static Guid guidVSPackage = new Guid(guidVSPackageString);
        public static Guid WebLinterCmdSet = new Guid(WebLinterCmdSetString);
        public static Guid ConfigFileCmdSet = new Guid(ConfigFileCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ContextMenuGroup = 0x1020;
        public const int LintFilesCommand = 0x0100;
        public const int FixLintErrorsCommand = 0x0150;
        public const int CleanErrorsCommand = 0x0200;
        public const int ToolsGroup = 0x1010;
        public const int ToolsMenu = 0x1020;
        public const int ToolsMenuGroup = 0x1030;
        public const int ToolsMenuResetGroup = 0x1040;
        public const int ResetConfigFiles = 0x0010;
        public const int EditTSLint = 0x0400;
    }
}
